owner: Parsepoint-Software
repo: upptime

sites:
  # Frontend App (Next.js)
  - name: Parsepoint App
    url: https://app-parsepoint.com

  # Backend API (Django on ECS)
  - name: Parsepoint API
    url: https://api.app-parsepoint.com/api/health/

  # Celery Worker (EC2)
  - name: Celery Worker
    url: 18.219.131.79
    port: 22
    check: tcp-ping

  # Marketing Website (Hostinger - needs browser User-Agent to avoid bot blocking)
  - name: Parsepoint Website
    url: https://parsepoint.com
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

status-website:
  publish: true
  cname: status.parsepoint.com
  name: Parsepoint Status
  introTitle: "**Parsepoint** System Status"
  introMessage: "Real-time status for Parsepoint services. Powered by [Upptime](https://github.com/upptime/upptime)."
  navbar:
    - title: Status
      href: /
    - title: Parsepoint
      href: https://parsepoint.com
