owner: Parsepoint-Software
repo: upptime

sites:
  # Frontend App (Next.js)
  - name: Parsepoint App
    url: https://app-parsepoint.com

  # Backend API (Django on ECS)
  - name: Parsepoint API
    url: https://api.app-parsepoint.com/api/health/

  # Celery Worker (EC2)
  - name: Celery Worker
    url: 18.219.131.79
    port: 22
    check: tcp-ping

  # Marketing Website
  - name: Parsepoint Website
    url: https://parsepoint.com

status-website:
  publish: true
  cname: status.parsepoint.com
  name: Parsepoint Status
  introTitle: "**Parsepoint** System Status"
  introMessage: "Real-time status for Parsepoint services. Powered by [Upptime](https://github.com/upptime/upptime)."
  navbar:
    - title: Status
      href: /
    - title: Parsepoint
      href: https://parsepoint.com
